name: 'Capistrano deploy'
description: 'Deploy an application using capistrano to the given target'
branding:
  icon: 'arrow-right-circle'
  color: 'black'
inputs:
  bundler_version:
    default: '1.17.3'
    description: 'The version of Bundler to install before running the bundle-command'
    required: true
  target:  # string
    description: 'Environment where deploy is to be performed to'
    required: false # if no param is given, default cap target will be selected
  deploy_key:
    description: 'Deployment key used for decryption of SSH RSA private key'
    required: true
  enc_rsa_key_pth:
    description: 'Path to SSH private key encrypted with deploy_key'
    required: true
    default: 'config/deploy_id_rsa_enc'
  working-directory:
    description: 'The directory from which to run the deploy command'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'lib/run.js'
